### PR TITLE
ripgrep 14.1.0

### PR DESCRIPTION
**Pull request by skupr-anaconda**
**Destination channel:** main

### Links

- [PKG-3672](https://anaconda.atlassian.net/browse/PKG-3672) 
- [Upstream repository](https://github.com/BurntSushi/ripgrep/tree/14.1.0)

### Explanation of changes:

- Add feedstock's license
- Reset the build number to 0
- Add `cargo-bundle-licenses`

[PKG-3672]: https://anaconda.atlassian.net/browse/PKG-3672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ifitchet** [comment]
README.md is a bit short on detail?

**Comment by skupr-anaconda** [comment]
> README.md is a bit short on detail?

@ifitchet Fixed

**Review by SC426 — APPROVED** [review]

**Comment by danpetry** [comment]
Is this ok? It's not using rust v1.76 in the end? same for other platforms
```
INFO       rust:                  1.76.0-h313beb8_0                                                                                                                                                
INFO       rust_osx-arm64:        1.71.1-h313beb8_0
...

INFO :: The inputs making up the hashes for the built packages are as follows:                                                                                                              
                   INFO   {                                                                                                                                                                                           
                   INFO     "ripgrep-14.1.0-h15d1925_0.tar.bz2": {                                                                                                                                                    
                   INFO       "recipe": {                                                                                                                                                                             
                   INFO         "channel_targets": "defaults",                                                                                                                                                        
                   INFO         "rust_compiler": "rust",                                                                                                                                                              
                   INFO         "rust_compiler_version": "1.71.1",                                                                                                                                                    
                   INFO         "target_platform": "osx-arm64"                                                                                                                                                        
                   INFO       }                                                                                                                                                                                       
                   INFO     }                                                                                                                                                                                         
                   INFO   }                 
```

**Comment by skupr-anaconda** [comment]
> Details



> Is this ok? It's not using rust v1.76 in the end? same for other platforms
> 
> ```
> INFO       rust:                  1.76.0-h313beb8_0                                                                                                                                                
> INFO       rust_osx-arm64:        1.71.1-h313beb8_0
> ...
> 
> INFO :: The inputs making up the hashes for the built packages are as follows:                                                                                                              
>                    INFO   {                                                                                                                                                                                           
>                    INFO     "ripgrep-14.1.0-h15d1925_0.tar.bz2": {                                                                                                                                                    
>                    INFO       "recipe": {                                                                                                                                                                             
>                    INFO         "channel_targets": "defaults",                                                                                                                                                        
>                    INFO         "rust_compiler": "rust",                                                                                                                                                              
>                    INFO         "rust_compiler_version": "1.71.1",                                                                                                                                                    
>                    INFO         "target_platform": "osx-arm64"                                                                                                                                                        
>                    INFO       }                                                                                                                                                                                       
>                    INFO     }                                                                                                                                                                                         
>                    INFO   }                 
> ```

Yeah, `conda-build` takes the `rust` version from the base `cbc.yaml` https://github.com/AnacondaRecipes/aggregate/blob/3752638c76c79b1b54c822b0a01e4cc047561146/conda_build_config.yaml#L38
I put a local `cbc.yaml` with rust 1.76.0 to the recipe.

**Comment by skupr-anaconda** [comment]
@danpetry Now it's built against rust 1.76.0:
```
  "ripgrep-14.1.0-h594256b_0.tar.bz2": {
    "recipe": {
      "channel_targets": "defaults",
      "rust_compiler": "rust",
      "rust_compiler_version": "1.76.0",
      "target_platform": "linux-64"
    }
```

**Review by ifitchet — APPROVED** [review]
LGTM

**Pull request merged**
